title: Meryem Manessouri
logo: /assets/img/m_elkhou800.png
description: Ph.D. C.V. USMBA | Junior Data Science | Artificial Intelligence | Computer Vision Engineer 
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
