title: Meryem MANESSOURI
logo: /assets/img/mimi.svg
description: Ph.D. NLP ERSC | Junior Data Science | Artificial Intelligence | Computer Vision Engineer 
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
email: meryem.manessouri@gmail.com
linkedin: https://www.linkedin.com/in/meryem-manessouri/
facebook: https://www.facebook.com/meryem.manessouri/
twitter: https://twitter.com/manessourimery1