title: Meryem Manessouri mm
logo: /assets/img/IMG_1660.jpg
description: Ph.D. NLP EMI | Junior Data Science | Artificial Intelligence | Computer Vision Engineer 
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
