title: Meryem Manessouri
logo: /assets/img/mimi.png
description: Ph.D. NLP EMI | Junior Data Science | Artificial Intelligence | Computer Vision Engineer
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
email: meryem.manessouri@gmail.com
linkedin: https://www.linkedin.com/in/meryem-manessouri/
facebook: https://www.facebook.com/meryem.manessouri/